### ISSUE TITLE
Feature Check - Web UI

### ISSUE THREAD

**Issue by Tvkoushik** [Linvest21-org/-TAKEN-python_ad-hoc-python-verifier#3]
Should we provide a Basic Web UI where the user can upload their python file for checking the syntax or executing the python code?

The Current MVP has a basic homepage which looks like this built using HTML, CSS and JS

<img width="1007" alt="image" src="https://github.com/Linvest21-org/-TAKEN-python_ad-hoc-python-verifier/assets/15716022/69481076-2f57-43c4-a188-00b41b47a951">

**Comment by mingbaolinvest21** [comment]
this task doesn't allow webUI, but, yes you need RESTAPI to allow file
uploads, and directory creation.

**Comment by Tvkoushik** [comment]
Sure, Will add that Functionality
